# https://medium.com/accenture-the-dock/when-how-to-deploy-kafka-on-kubernetes-b18f5270db63
apiVersion: v1
kind: Namespace
metadata:
  name: "kafka-cluster"
  labels:
    name: "kafka-cluster"
---

kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: zookeeper-deployment-1
  namespace: kafka-cluster
spec:
  serviceName: zoo1
  replicas: 1
  selector:
    matchLabels:
      name: zookeeper-1
  template:
    spec:
      nodeSelector:
        nodeType: memory-eu-west
      containers:
        - name: zoo1
          image: digitalwonderland/zookeeper
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_ID
              value: "1"
            - name: ZOOKEEPER_SERVER_1
              value: zoo1
            - name: ZOOKEEPER_SERVER_2
              value: zoo2
            - name: ZOOKEEPER_SERVER_3
              value: zoo3
          volumeMounts:
            - name: efs-volume
              mountPath: "/var/lib/zookeeper"
      volumes:
        - name: efs-volume
          nfs:
            server: xxxxxxx.efs.eu-west-1.amazonaws.com
            path: /vol/zk/data/zoo1
---
apiVersion: v1
kind: Service
metadata:
  name: zoo1
  namespace: kafka-cluster
  labels:
    app: zookeeper-1
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
  selector:
    app: zookeeper-1
---

apiVersion: v1
kind: Service
metadata:
  name: kafka1
  namespace: kafka-cluster
  labels:
    app: kafka-broker-1
spec:
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    app: kafka-broker-1
  type: LoadBalancer
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: kafka-deployment-1
  namespace: kafka-cluster
spec:
  serviceName: kafka1
  replicas: 1
  selector:
    matchLabels:
      name: kafka-broker-1
  template:
    spec:
      nodeSelector:
        servertype: analytics
      containers:
        - name: kafka
          image: wurstmeister/kafka:2.11-2.0.1
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "load-balancer URL"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo1:2181,zoo2:2181,zoo3:2181
            - name: KAFKA_CREATE_TOPICS
              value: "test-topic:3:2:compact"
            - name: KAFKA_LOG_DIRS
              value: /kafka/kafka-logs
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_JMX_PORT
              value: "5555"
            - name: KAFKA_CLEANUP_POLICY
              value: "compact"
          volumeMounts:
            - name: xr-volume
              mountPath: "/kafka/kafka-logs"
      volumes:
        - name: xr-volume
          nfs:
            server: xxxxx.efs.eu-west-1.amazonaws.com
            path: /kafka-k8/logs/broker1