#server:
# port: 8080
# servlet:
#   context-path: /resource-server

spring:
  main:
    log-startup-info: false

# son:
  # property-naming-strategy: UPPER_CAMEL_CASE
  # serialization:
    # indent-output: true