DROP TABLE IF EXISTS Artist;
DROP TABLE IF EXISTS Song;

CREATE TABLE Artist (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    country VARCHAR(250) NOT NULL
);

CREATE TABLE Song (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    title VARCHAR(250) NOT NULL,
    artist VARCHAR(250) NOT NULL
);
